twig:
  default_path: '%kernel.project_dir%/templates'
  paths:
    - '%admin_theme_dir%/template'

  globals:
    PHYXO_VERSION: '%core_version%'
    PHYXO_URL: '%phyxo_website%'

  exception_controller: null

  strict_variables: '%kernel.debug%'

  form_themes: ['bootstrap_4_layout.html.twig', 'form/_theme.html.twig']

when@dev:
    twig:
        strict_variables: true
