albums_flat__start:
  path:  /albums/flat/start-{start}
  controller: App\Controller\AlbumController::albumsFlat
  defaults:
    start: 0
  requirements:
    start: \d+

albums_flat:
  path:  /albums/flat
  controller: App\Controller\AlbumController::albumsFlat
  defaults:
    start: 0

albums__start:
  path: /albums/start-{start}
  controller: App\Controller\AlbumController::albums
  requirements:
    start: \d+

albums:
  path: /albums
  controller: App\Controller\AlbumController::albums
  defaults:
    start: 0

album__start:
  path: /album/{album_id}/start-{start}
  controller: App\Controller\AlbumController::album
  defaults:
    start: 0
  requirements:
    start: \d+

album:
  path: /album/{album_id}
  controller: App\Controller\AlbumController::album
  defaults:
    start: 0

album_flat__start:
  path: /album/{album_id}/flat/start-{start}
  controller: App\Controller\AlbumController::albumFlat
  defaults:
    start: 0
    extra_params: flat
  requirements:
    start: \d+

album_flat:
  path: /album/{album_id}/flat
  controller: App\Controller\AlbumController::albumFlat
  defaults:
    start: 0
    extra_params: flat
