calendar:
  path: /calendar/{date_type}
  controller: App\Controller\CalendarController::index
  defaults:
    start: 0
    date_type: '%default_date_type%'
  requirements:
    date_type: created|posted


calendar_by_year__start:
  path: /calendar/{date_type}/{year}/start-{start}
  controller: App\Controller\CalendarController::byYear
  defaults:
    date_type: '%default_date_type%'
  requirements:
    start: \d+
    date_type: created|posted
    year: \d{4}

calendar_by_year:
  path: /calendar/{date_type}/{year}
  controller: App\Controller\CalendarController::byYear
  defaults:
    start: 0
    date_type: '%default_date_type%'
  requirements:
    date_type: created|posted
    year: \d{4}

calendar_by_month__start:
  path: /calendar/{date_type}/{year}/{month}/start-{start}
  controller: App\Controller\CalendarController::byMonth
  defaults:
    date_type: '%default_date_type%'
  requirements:
    start: \d+
    date_type: created|posted
    year: \d{4}
    month: \d{2}

calendar_by_month:
  path: /calendar/{date_type}/{year}/{month}
  controller: App\Controller\CalendarController::byMonth
  defaults:
    start: 0
    date_type: '%default_date_type%'
  requirements:
    date_type: created|posted
    year: \d{4}
    month: \d{2}

calendar_by_day__start:
  path: /calendar/{date_type}/{year}/{month}/{day}/start-{start}
  controller: App\Controller\CalendarController::byDay
  defaults:
    date_type: '%default_date_type%'
  requirements:
    start: \d+
    date_type: created|posted
    year: \d{4}
    month: \d{2}
    day: \d{2}

calendar_by_day:
  path: /calendar/{date_type}/{year}/{month}/{day}
  controller: App\Controller\CalendarController::byDay
  defaults:
    start: 0
    date_type: '%default_date_type%'
  requirements:
    date_type: created|posted
    year: \d{4}
    month: \d{2}
    day: \d{2}
