comment_edit:
  path: /comments/{start}/edit/{comment_id}
  controller: App\Controller\CommentController::index
  defaults:
    start: 0
  requirements:
    start: \d+
    comment_id: \d+

comments__start:
  path: /comments/start-{start}
  controller: App\Controller\CommentController::index
  defaults:
    comment_id: 0
    start: 0
  requirements:
    start: \d+

comments:
  path: /comments
  controller: App\Controller\CommentController::index
  defaults:
    start: 0
    comment_id: 0

comment_validate:
  path: /comments/validate/{comment_id}
  controller: App\Controller\CommentController::validateComment
  defaults:
    start: 0
    comment_id: \d+

comment_update:
  path: /comments/update/{comment_id}
  controller: App\Controller\CommentController::updateComment
  defaults:
    start: 0
    comment_id: \d+

comment_delete:
  path: /comments/delete/{comment_id}
  controller: App\Controller\CommentController::deleteComment
  defaults:
    start: 0
    comment_id: \d+
