homepage:
  path: /
  controller: App\Controller\DefaultController::home

about:
  path: /about
  controller: App\Controller\AboutController::index

feed:
  path: /feed/{feed_id}
  controller: App\Controller\FeedController::feed

feed_image_only:
  path: /feed/{feed_id}/image-only
  controller: App\Controller\FeedController::feed
  defaults:
    image_only: true

notification:
  path: /notification
  controller: App\Controller\FeedController::notification

notification_subscribe:
  path: /notification/subscribe
  controller: App\Controller\FeedController::notificationSubscribe

notification_unsubscribe:
  path: /notification/unsubscribe
  controller: App\Controller\FeedController::notificationUnsubscribe

ws:
  path: /ws
  controller: App\Controller\WsController::index

media:
  path: /media/{path}-{derivative}.{image_extension}
  controller: App\Controller\MediaController::index
  requirements:
    path: '[^_]*'
    derivative: sq|th|2s|xs|sm|me|la|xl|xx
    image_extension: jpg|jpeg|png
    sizes: '(?:|_[^\.]*)'
  defaults:
    sizes: ''

media_custom:
  path: /media/{path}-cu_{sizes}.{image_extension}
  controller: App\Controller\MediaController::index
  requirements:
    path: '[^_]*'
    image_extension: jpg|jpeg|png
    sizes: 'e[^\.]*'
  defaults:
    derivative: cu

plugin_asset:
  path: /asset/plugin/{id}/{path}
  controller: App\Controller\ExtensionAssetController::pluginAsset
  requirements:
    id: '[^/]*'
    path: '.+'

theme_asset:
  path: /asset/theme/{id}/{path}
  controller: App\Controller\ExtensionAssetController::themeAsset
  requirements:
    id: '[^/]*'
    path: '.+'

action:
  path: /action/{image_id}/{part}/{download}
  controller: App\Controller\DefaultController::action
  defaults:
    download: false
  requirements:
    image_id: \d+
    part: e|r
    download: download
