homepage:
  path: /
  controller: App\Controller\DefaultController::home

about:
  path: /about
  controller: App\Controller\AboutController::index

feed:
  path: /feed/{feed_id}
  controller: App\Controller\FeedController::feed

feed_image_only:
  path: /feed/{feed_id}/image-only
  controller: App\Controller\FeedController::feed
  defaults:
    image_only: true

notification:
  path: /notification
  controller: App\Controller\FeedController::notification

notification_subscribe:
  path: /notification/subscribe
  controller: App\Controller\FeedController::notificationSubscribe

notification_unsubscribe:
  path: /notification/unsubscribe
  controller: App\Controller\FeedController::notificationUnsubscribe

ws:
  path: /ws
  controller: App\Controller\WsController::index

media:
  path: /media/{path}-{derivative}.{image_extension}
  controller: App\Controller\MediaController::derivative
  requirements:
    path: '.*'
    derivative: sq|th|2s|xs|sm|me|la|xl|xx
    image_extension: jpg|jpeg|png|mp4

media_custom:
  path: /media/{path}-cu_{sizes}.{image_extension}
  controller: App\Controller\MediaController::custom
  requirements:
    path: '.*'
    image_extension: jpg|jpeg|png|mp4
    sizes: '(e|s)[^\.]*'
  defaults:
    derivative: cu

media_original:
  path: /media/{path}.{image_extension}
  controller: App\Controller\MediaController::original
  requirements:
    path: '[^_]*'
    image_extension: jpg|jpeg|png

plugin_asset:
  path: /asset/plugin/{id}/{path}
  controller: App\Controller\ExtensionAssetController::pluginAsset
  requirements:
    id: '[^/]*'
    path: '.+'

theme_asset:
  path: /asset/theme/{id}/{path}
  controller: App\Controller\ExtensionAssetController::themeAsset
  requirements:
    id: '[^/]*'
    path: '.+'

download_picture:
  path: /download/{image_id}
  controller: App\Controller\DefaultController::download
  requirements:
    image_id: '[^/]*'

public_menubar_navigation:
  path: /menubar_navigation
  controller: App\Controller\MenubarController::navigation
