UPDATE phyxo_user_infos SET language = 'en_GB';

DELETE FROM phyxo_languages;
INSERT INTO phyxo_languages (id,version,name) VALUES('es_AR', '1.6.0', 'Argentina [AR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('en_UK', '1.6.0', 'English [UK]');
INSERT INTO phyxo_languages (id,version,name) VALUES('fr_FR', '1.6.0', 'Français [FR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('af_ZA', '1.6.0', 'Afrikaans [ZA]');
INSERT INTO phyxo_languages (id,version,name) VALUES('az_AZ', '1.6.0', 'Azərbaycanca [AZ]');
INSERT INTO phyxo_languages (id,version,name) VALUES('id_ID', '1.6.0', 'Bahasa Indonesia [ID]');
INSERT INTO phyxo_languages (id,version,name) VALUES('pt_BR', '1.6.0', 'Brasil [BR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('br_FR', '1.6.0', 'Brezhoneg [FR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ca_ES', '1.6.0', 'Català [CA]');
INSERT INTO phyxo_languages (id,version,name) VALUES('da_DK', '1.6.0', 'Dansk [DK]');
INSERT INTO phyxo_languages (id,version,name) VALUES('de_DE', '1.6.0', 'Deutsch [DE]');
INSERT INTO phyxo_languages (id,version,name) VALUES('dv_MV', '1.6.0', 'Dhivehi [MV]');
INSERT INTO phyxo_languages (id,version,name) VALUES('en_GB', '1.6.0', 'English [GB]');
INSERT INTO phyxo_languages (id,version,name) VALUES('en_US', '1.6.0', 'English [US]');
INSERT INTO phyxo_languages (id,version,name) VALUES('es_ES', '1.6.0', 'Español [ES]');
INSERT INTO phyxo_languages (id,version,name) VALUES('eo_EO', '1.6.0', 'Esperanto [EO]');
INSERT INTO phyxo_languages (id,version,name) VALUES('et_EE', '1.6.0', 'Estonian [EE]');
INSERT INTO phyxo_languages (id,version,name) VALUES('eu_ES', '1.6.0', 'Euskara [ES]');
INSERT INTO phyxo_languages (id,version,name) VALUES('fi_FI', '1.6.0', 'Finnish [FI]');
INSERT INTO phyxo_languages (id,version,name) VALUES('fr_CA', '1.6.0', 'Français [QC]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ga_IE', '1.6.0', 'Gaeilge [IE]');
INSERT INTO phyxo_languages (id,version,name) VALUES('gl_ES', '1.6.0', 'Galego [ES]');
INSERT INTO phyxo_languages (id,version,name) VALUES('hr_HR', '1.6.0', 'Hrvatski [HR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('it_IT', '1.6.0', 'Italiano [IT]');
INSERT INTO phyxo_languages (id,version,name) VALUES('lv_LV', '1.6.0', 'Latviešu [LV]');
INSERT INTO phyxo_languages (id,version,name) VALUES('lt_LT', '1.6.0', 'Lietuviu [LT]');
INSERT INTO phyxo_languages (id,version,name) VALUES('lb_LU', '1.6.0', 'Lëtzebuergesch [LU]');
INSERT INTO phyxo_languages (id,version,name) VALUES('hu_HU', '1.6.0', 'Magyar [HU]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ms_MY', '1.6.0', 'Malay [MY]');
INSERT INTO phyxo_languages (id,version,name) VALUES('es_MX', '1.6.0', 'México [MX]');
INSERT INTO phyxo_languages (id,version,name) VALUES('nl_NL', '1.6.0', 'Nederlands [NL]');
INSERT INTO phyxo_languages (id,version,name) VALUES('nb_NO', '1.6.0', 'Norwegian [NO]');
INSERT INTO phyxo_languages (id,version,name) VALUES('nn_NO', '1.6.0', 'Norwegian nynorsk [NO]');
INSERT INTO phyxo_languages (id,version,name) VALUES('pl_PL', '1.6.0', 'Polski [PL]');
INSERT INTO phyxo_languages (id,version,name) VALUES('pt_PT', '1.6.0', 'Português [PT]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ro_RO', '1.6.0', 'Română [RO]');
INSERT INTO phyxo_languages (id,version,name) VALUES('sk_SK', '1.6.0', 'Slovensky [SK]');
INSERT INTO phyxo_languages (id,version,name) VALUES('sl_SI', '1.6.0', 'Slovenšcina [SI]');
INSERT INTO phyxo_languages (id,version,name) VALUES('sh_RS', '1.6.0', 'Srpski [SR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('sv_SE', '1.6.0', 'Svenska [SE]');
INSERT INTO phyxo_languages (id,version,name) VALUES('vi_VN', '1.6.0', 'Tiếng Việt [VN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('tr_TR', '1.6.0', 'Türkçe [TR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('wo_SN', '1.6.0', 'Wolof [SN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('is_IS', '1.6.0', 'Íslenska [IS]');
INSERT INTO phyxo_languages (id,version,name) VALUES('cs_CZ', '1.6.0', 'Česky [CZ]');
INSERT INTO phyxo_languages (id,version,name) VALUES('el_GR', '1.6.0', 'Ελληνικά [GR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('bg_BG', '1.6.0', 'Български [BG]');
INSERT INTO phyxo_languages (id,version,name) VALUES('mk_MK', '1.6.0', 'Македонски [MK]');
INSERT INTO phyxo_languages (id,version,name) VALUES('mn_MN', '1.6.0', 'Монгол [MN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ru_RU', '1.6.0', 'Русский [RU]');
INSERT INTO phyxo_languages (id,version,name) VALUES('sr_RS', '1.6.0', 'Српски [SR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('uk_UA', '1.6.0', 'Українська [UA]');
INSERT INTO phyxo_languages (id,version,name) VALUES('he_IL', '1.6.0', 'עברית [IL]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ar_SA', '1.6.0', 'العربية [AR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ar_MA', '1.6.0', 'العربية [MA]');
INSERT INTO phyxo_languages (id,version,name) VALUES('fa_IR', '1.6.0', 'پارسی [IR]');
INSERT INTO phyxo_languages (id,version,name) VALUES('kok_IN', '1.6.0', ' कोंकणी [IN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('bn_IN', '1.6.0', 'বাংলা[IN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('gu_IN', '1.6.0', 'ગુજરાતી[IN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ta_IN', '1.6.0', 'தமிழ் [IN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('kn_IN', '1.6.0', 'ಕನ್ನಡ [IN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('th_TH', '1.6.0', 'ภาษาไทย [TH]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ka_GE', '1.6.0', 'ქართული [GE]');
INSERT INTO phyxo_languages (id,version,name) VALUES('km_KH', '1.6.0', 'ខ្មែរ [KH]');
INSERT INTO phyxo_languages (id,version,name) VALUES('zh_TW', '1.6.0', '中文 (繁體) [TW]');
INSERT INTO phyxo_languages (id,version,name) VALUES('zh_HK', '1.6.0', '中文 (香港) [HK]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ja_JP', '1.6.0', '日本語 [JP]');
INSERT INTO phyxo_languages (id,version,name) VALUES('zh_CN', '1.6.0', '简体中文 [CN]');
INSERT INTO phyxo_languages (id,version,name) VALUES('ko_KR', '1.6.0', '한국어 [KR]');
