admin_album:
  path: /album/{album_id}/edit/{parent_id}
  controller: App\Controller\Admin\AdminAlbumController:properties
  defaults:
    parent_id: null
  requirements:
    album_id: \d+
    parent_id: \d+

admin_album_sort_order:
  path: /album/{album_id}/sort_order/{parent_id}
  controller: App\Controller\Admin\AdminAlbumController:sort_order
  defaults:
    parent_id: null
  requirements:
    album_id: \d+
    parent_id: \d+

admin_album_permissions:
  path: /album/{album_id}/permissions/{parent_id}
  controller: App\Controller\Admin\AdminAlbumController:permissions
  defaults:
    parent_id: null
  requirements:
    album_id: \d+
    parent_id: \d+

admin_album_notification:
  path: /album/{album_id}/notification/{parent_id}
  controller: App\Controller\Admin\AdminAlbumController:notification
  defaults:
    parent_id: null
  requirements:
    album_id: \d+
    parent_id: \d+

admin_album_create:
  path: /album/create/{parent_id}
  controller: App\Controller\Admin\AdminAlbumController:create
  methods: ['POST']
  defaults:
    parent_id: null
  requirements:
    parent_id: \d+

admin_album_delete:
  path: /album/{album_id}/delete/{parent_id}
  controller: App\Controller\Admin\AdminAlbumController:delete
  defaults:
    parent_id: null
  requirements:
    album_id: \d+
    parent_id: \d+
