admin_albums:
  path: /albums/{parent_id}
  controller: App\Controller\Admin\AdminAlbumsController:list
  defaults:
    parent_id: null
  requirements:
    parent_id: \d+

admin_albums_update:
  path: /albums/update/{parent_id}
  controller: App\Controller\Admin\AdminAlbumsController:update
  methods: ['POST']
  defaults:
    parent_id: null
  requirements:
    parent_id: \d+

admin_albums_move:
  path: /albums/move/{parent_id}
  controller: App\Controller\Admin\AdminAlbumsController:move
  defaults:
    parent_id: null
  requirements:
    parent_id: \d+

admin_albums_options:
  path: /albums/options/{section}
  controller: App\Controller\Admin\AdminAlbumsOptionsController:index
  defaults:
    section: status
  requirements:
    section: status|lock|comments|representative
