admin_batch_manager_global:
  path: /batch/global/{filter}/{value}
  controller: App\Controller\Admin\AdminBatchManagerController::global
  defaults:
    filter: null
    value: null
    start: 0
  requirements:
    filter: caddie|favorites|last_import|album|no_album|tag|no_tag|duplicates|all_photos

admin_batch_manager_global__start:
  path: /batch/global/{start}/{filter}/{value}
  controller: App\Controller\Admin\AdminBatchManagerController::global
  defaults:
    filter: null
    value: null
  requirements:
    filter: caddie|favorites|last_import|album|no_album|tag|no_tag|duplicates|all_photos
    start: \d+

admin_batch_manager_global_empty_caddie:
  path: /batch/global/empty_caddie/{start}
  controller: App\Controller\Admin\AdminBatchManagerController::emptyCaddie
  defaults:
    start: 0
  requirements:
    start: \d+

admin_batch_manager_unit:
  path: /batch/unit/{filter}/{value}
  controller: App\Controller\Admin\AdminBatchManagerController::unit
  defaults:
    filter: null
    value: null
    start: 0
  requirements:
    filter: caddie|favorites|last_import|album|no_album|tag|no_tag|duplicates|all_photos

admin_batch_manager_unit__start:
  path: /batch/unit/{start}/{filter}/{value}
  controller: App\Controller\Admin\AdminBatchManagerController::unit
  defaults:
    filter: null
    value: null
  requirements:
    filter: caddie|favorites|last_import|album|no_album|tag|no_tag|duplicates|all_photos
    start: \d+
