admin_configuration_sizes_restore:
  path: /configuration/sizes/restore
  controller: App\Controller\Admin\AdminConfigurationController:sizeRestore

# options
admin_configuration:
  path: /configuration/{section}
  controller: App\Controller\Admin\AdminConfigurationController:index
  defaults:
    section: main
  requirements:
    section: main|sizes|watermark|display|comments|default

admin_configuration_update:
  path: /configuration/{section}/update
  controller: App\Controller\Admin\AdminConfigurationController:update
  defaults:
    section: main
  requirements:
    section: main|sizes|watermark|display|comments|default
  methods: POST
