admin_history_search:
  path: /history/search/{search_id}
  controller: App\Controller\Admin\AdminHistoryController::search
  defaults:
    search_id: null
    start: 0
  requirements:
    search_id: \d+

admin_history_search__start:
  path: /history/search/{search_id}/{start}
  controller: App\Controller\Admin\AdminHistoryController::search
  defaults:
    search_id: null
  requirements:
    start: \d+
    search_id: \d+

admin_history:
  path: /history
  controller: App\Controller\Admin\AdminHistoryController::stats

admin_history_year:
  path: /history/{year}
  controller: App\Controller\Admin\AdminHistoryController::stats
  requirements:
    year: \d{4}

admin_history_year_month:
  path: /history/{year}/{month}
  controller: App\Controller\Admin\AdminHistoryController::stats
  requirements:
    year: \d{4}
    month: \d{2}

admin_history_year_month_day:
  path: /history/{year}/{month}/{day}
  controller: App\Controller\Admin\AdminHistoryController::stats
  requirements:
    year: \d{4}
    month: \d{2}
    day: \d{2}
