install:
  path: /install/{step}
  controller: App\Controller\InstallController::index
  defaults:
    step: language
  requirements:
    step: language|check|database|user|success

admin_upgrade:
  path: /upgrade
  controller: App\Controller\AdminController::upgrade

admin_check_upgrade:
  path: /check_upgrade
  controller: App\Controller\Admin\AdminDashboardController::index
  defaults:
    check_upgrade: true

admin_home:
  path: /
  controller: App\Controller\Admin\AdminDashboardController::index
  defaults:
    check_upgrade: false

admin_menubar:
  path: /menubar
  controller: App\Controller\Admin\AdminMenubarController::index

admin_menubar_update:
  path: /menubar/update
  controller: App\Controller\Admin\AdminMenubarController::update
  methods: POST

admin_menubar_navigation:
  path: /menubar_navigation
  controller: App\Controller\Admin\AdminMenubarController::navigation

api:
  path: /api
  controller: App\Controller\Admin\AdminApiController::index
