admin_media:
  path: /media/{path}-{derivative}.{image_extension}
  controller: App\Controller\MediaController::mediaForAdmin
  requirements:
    path: '[^_]*'
    derivative: sq|th|2s|xs|sm|me|la|xl|xx
    image_extension: jpg|jpeg|png
    sizes: '(?:|_[^\.]*)'
  defaults:
    sizes: ''
