admin_notification:
  path: /notification
  controller: App\Controller\Admin\AdminNotificationController:params

admin_notification_subscribe:
  path: /notification/subscribe
  controller: App\Controller\Admin\AdminNotificationController:subscribe

admin_notification_send:
  path: /notification/send
  controller: App\Controller\Admin\AdminNotificationController:send
