admin_photos_add:
  path: /photos/add/{album_id}
  controller: App\Controller\Admin\AdminPhotosController:direct
  defaults:
    album_id: null
  requirements:
    album_id: \d+

admin_photos_add_batch:
  path: /photos/batch/{album_id}
  controller: App\Controller\Admin\AdminPhotosController:batch
  methods: ['POST']
  defaults:
    album_id: null
  requirements:
    album_id: \d+
