admin_site:
  path: /site
  controller: App\Controller\Admin\AdminSiteController:index

admin_site_delete:
  path: /site/delete
  controller: App\Controller\Admin\AdminSiteController:delete
  methods: ['POST']

admin_synchronize:
  path: /synchronize/{site}
  controller: App\Controller\Admin\AdminSiteController:synchronize
  requirements:
    site: \d+
