# themes
admin_themes_installed:
  path: /themes
  controller: App\Controller\Admin\AdminThemesController::installed

admin_themes_new:
  path: /themes/new
  controller: App\Controller\Admin\AdminThemesController::new

admin_themes_update:
  path: /themes/update
  controller: App\Controller\Admin\AdminThemesController::update

admin_themes_action:
  path: /themes/{action}/{theme}
  controller: App\Controller\Admin\AdminThemesController::action
  requirements:
    action: activate|deactivate|delete|set_default
    theme: .+

admin_themes_install:
  path: /themes/install/{revision}
  controller: App\Controller\Admin\AdminThemesController::install
  requirements:
    revision: \d+

admin_theme_screenshot:
  path: /theme/screenshot/{theme}
  controller: App\Controller\Admin\AdminThemesController::screenshot
