admin_update:
  path: /update/{step}/{version}
  controller: App\Controller\Admin\AdminUpdateController::core
  defaults:
    step: 0
    version: null
  requirements:
    step: \d+

admin_update_extensions:
  path: /update/extensions
  controller: App\Controller\Admin\AdminUpdateController::extensions
