admin_users:
  path: /users
  controller: App\Controller\Admin\AdminUsersController:list

admin_user_perm:
  path: /user/{user_id}/perm
  controller: App\Controller\Admin\AdminUsersController:perm
  requirements:
    user_id: \d+
