name: Phyxo

on: [push]

jobs:
  tests:
    name: Phyxo tests
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: [7.3, 7.4]
        mysql: [5.7, 8.0]

    env:
      APP_ENV: test
      DATABASE_URL: 'mysql://root:root@127.0.0.1/phyxo?serverVersion=${{ matrix.mysql }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shutdown default MySQL
        run: sudo service mysql stop

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '${{ matrix.mysql }}'
          mysql root password: 'root'

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v1
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, mysql, pdo_mysql
        env:
          update: true

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: composer phpstan

      - name: Unit tests
        run: ./bin/atoum

  release:
    name: Phyxo release
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v1
          php-version: '7.3'
          coverage: xdebug
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        env:
          update: true

      - name: Install dependencies
        run: composer install

      - name: Setup Phyxo version
        run: |
          echo "PHYXO_VERSION=$(make version)" >> $GITHUB_ENV

      - name: Build archive
        run: make build

      - name: Archive nightly build
        uses: actions/upload-artifact@v2
        with:
          name: phyxo-${{ env.PHYXO_VERSION }}
          path: .dist
