name: Phyxo

on: [push]

jobs:
  tests:
    name: Phyxo tests
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.php-version == '8.4' }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: [8.2, 8.3, 8.4]
        mysql: [5.7]

    env:
      APP_ENV: test
      DATABASE_URL: 'mysql://root:root@127.0.0.1/phyxo?serverVersion=${{ matrix.mysql }}'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Shutdown default MySQL
        run: sudo service mysql stop

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '${{ matrix.mysql }}'
          mysql root password: 'root'

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          tools: composer, symfony-cli
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, mysql, pdo_mysql
        env:
          APP_ENV: test
          DATABASE_URL: "mysql://root:root@localhost/phyxo"

      - name: Install dependencies
        run: composer install

      - name: Cache warmup
        run: ./bin/console cache:warmup

      - name: Run PHPStan
        run: composer phpstan

      - name: Create database
        run: ./bin/console doctrine:database:create -vvv

      - name: Install Phyxo
        run: ./bin/console phyxo:install -vvv

      - name: Create guest user
        run: ./bin/console phyxo:user:create --username guest --password '' --mail_address '' --status guest

      - name: Unit tests
        run: composer phpunit

      - name: Fake admin theme
        run: mkdir -p public/admin/theme/build && echo '{}' > public/admin/theme/build/manifest.json

      - name: symfony local server
        run: symfony server:start --port 1080 --no-tls --daemon

      - name: Run Behat tests
        run: ./bin/behat --colors --no-interaction -vvv -c behat.yml.dist  --suite=web
  #
  # release:
  #   name: Phyxo release
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup PHP, extensions and composer with shivammathur/setup-php
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         tools: composer:v1
  #         php-version: '7.3'
  #         coverage: xdebug
  #         extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
  #       env:
  #         update: true
  #     - name: Install dependencies
  #       run: composer install
  #     - name: Setup Phyxo version
  #       run: |
  #         echo "PHYXO_VERSION=$(make version)" >> $GITHUB_ENV
  #     - name: Build archive
  #       run: make build
  #     - name: Archive nightly build
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: phyxo-${{ env.PHYXO_VERSION }}
  #         path: .dist
